# Generated by Django 5.0.8 on 2025-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('delivery_man', 'Delivery Man'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
